using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;

namespace QLST
{
    public partial class Customers : DevExpress.XtraEditors.XtraForm
    {
        public static string ID;
        public Customers()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {
            var cellvalue = cus_info.GetRowCellValue(cus_info.FocusedRowHandle,CusID);
            ID = cellvalue.ToString();
            Customer_Info customer_info = new Customer_Info();
            customer_info.ShowDialog();
        }

        private void Customers_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'customer_ds.Customers' table. You can move, or remove it, as needed.
            this.customersTableAdapter.Fill(this.customer_ds.Customers);

            // TODO: This line of code loads data into the 'customer1.Customers' table. You can move, or remove it, as needed.

            // TODO: This line of code loads data into the 'superMarketDataSet1.Customers' table. You can move, or remove it, as needed.

            // TODO: This line of code loads data into the 'superMarketDataSet.Customers' table. You can move, or remove it, as needed.


        }

        private void tableLayoutPanel1_Paint(object sender, PaintEventArgs e)
        {

        }
    }
}